[build]
  command = "npm run build"
  publish = "generated"
  functions = "functions"

# Redirect all 404s to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[dev]
  autoLaunch = false
  framework = "#static"
  targetPort = 3000

[context.production.environment]
  NODE_VERSION = "16.20.2"  # Explicit version instead of '16.x'