[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[context.production.environment]
  NODE_VERSION = "16.20.2"

[build.environment]
  NODE_VERSION = "16.20.2"