[build]
  command = "npm run build"
  publish = "generated"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  CI = false

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control and security headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Development settings
[dev]
  autoLaunch = false
  framework = "#static"
  targetPort = 3000
  publish = "generated"

# Context-specific settings
[context.production]
  command = "npm run build"
  environment = { 
    NODE_ENV = "production",
    GENERATE_SOURCEMAP = "false"
  }

[context.deploy-preview]
  command = "npm run build"
  environment = { 
    NODE_ENV = "development" 
  }

[context.branch-deploy]
  command = "npm run build"
  environment = { 
    NODE_ENV = "development" 
  }